substitutions:
  $_CLOUDSDK_COMPUTE_REGION :  us-central1  # default value
  $_CLOUDSDK_COMPUTE_ZONE: us-central1-c    # default value
  $_CLOUDSDK_CONTAINER_CLUSTER: cluster-1   # default value
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/$PROJECT_ID/$_PROJECT:$SHORT_SHA','.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/$PROJECT_ID/$_PROJECT:$SHORT_SHA']

#- name: 'gcr.io/cloud-builders/gcloud'
#  args: ['config','set','project','${_PROJECT}']

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply','-f','python-service','--image','gcr.io/$PROJECT_ID/$_PROJECT:$SHORT_SHA','--region','us-central1','--platform','managed','--memory','8Gi','--cpu','8']

images: ['gcr.io/$PROJECT_ID/$_PROJECT:$SHORT_SHA']

