substitutions:
   _CLOUDSDK_COMPUTE_ZONE= us-central1-c
   _CLOUDSDK_CONTAINER _CLUSTER= cluster-1

steps:

- id: "to build the image"
  name: "gcr.io/cloud-builders/docker"
  args: ["build","-t","gcr.io/$PROJECT_ID/$REPO_NAME/$BRANCH_NAME:$SHORT_SHA","."]

- id: "to push the image"
  name: "gcr.io/cloud-builders/docker"
  args: ["push","gcr.io/$PROJECT_ID/$REPO_NAME/$BRANCH_NAME:$SHORT_SHA"]

#- id: "to set image in deployment yaml"
 # name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #entrypoint: gcloud
  #args: ['run', 'deploy', 'python-flask-app', '--image', 'gcr.io/$PROJECT_ID/$REPO_NAME/$BRANCH_NAME:$SHORT_SHA', '--region', 'us-central1']
#images: [gcr.io/$PROJECT_ID/$REPO_NAME/$BRANCH_NAME:$SHORT_SHA]


#- id: kubectl-apply
 # name: 'gcr.io/cloud-builders/kubectl'
  #args: ['apply', '-f', $_CONFIGURATION_FILE, '-n',  $_NAMESPACE]