steps:
- name: python
  args: ["-m","pip","install","--upgarde","pip"]
- name: python
  args: ["-m","pip","install","Flask","pip","--user"]
- name: "gcr.io/cloud-builders/docker"
  args: ["build","-t","python-app","."]
- name: "gcr.io/cloud-builders/docker"
  args: ["push","python-app"]
