steps:

- id: "to build the image"
  name: "gcr.io/cloud-builders/docker"
  args: ["build","-t","gcr.io/vidhi-try/python-flask-app","."]

- id: "to push the image"
  name: "gcr.io/cloud-builders/docker"
  args: ["push","gcr.io/vidhi-try/python-flask-app"]

