steps:
#step 1
- name: 'gcr.io/cloud-builders/docker' 
  entrypoint: 'bash'
  args: [
   '-c', 
   'docker pull gcr.io/$PROJECT_ID/$_PROJECT:$SHORT_SHA' 
  ]
#step 2
- name: gcr.io/cloud-builders/docker
  args: [
   'build', 
   '-t', 
   'gcr.io/$PROJECT_ID/$_PROJECT:$SHORT_SHA' ,
   '.'
  ]
#step 3
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', '$__CONFIGURATION_FILE']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster1'
#step 4
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
   'set', 
   'image', 
   'deployment', 
   $_PROJECT', 
   '$_PROJECT=gcr.io/$PROJECT_ID/$_PROJECT:$SHORT_SHA'
  ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE= us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER= cluster1'
# push images to Google Container Registry with tags
images: ['gcr.io/$PROJECT_ID/$_PROJECT:$SHORT_SHA']

