apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-flask-deployment
  labels:
    app: python-flask
spec:
  replicas: 1
  selector:
     matchLabels:
       app: python-flask
  template:
    metadata:
      labels:
        app: python-flask
    spec:
      containers:
      - name: python-flask
        image: IMAGE_VALUE:IMAGE_TAG
        env:
        - name: REDIS_HOST
          value: "redis-master"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_DB
          value: "0"
        - name: REDIS_PASSWORD
          value: "SUZRNUw3YUFDbw=="
        ports:
        - containerPort : 9595
        resources:
          requests:
            memory: 50Mi
            cpu: 200m
          limits:
            memory: 100Mi
            cpu: 500m

---

apiVersion: v1
kind: Service
metadata:
  name: python-flask-service-lb
spec:
  type: LoadBalancer
  ports:
  - port: 9595
    targetPort: 9595
  selector:
    app: python-flask


