apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-flask-app
  template:
    metadata:
      labels:
        app:  python-flask-app
    spec:
      containers:
      - name: python-flask-app
        image: IMAGE_VALUE
        ports:
        - containerPort: 9595

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-flask-app
spec:
  tls:
  - hosts:
    - sdv.com
    secretName: sdv-tls
  rules:
  - host: sdv.com
    http:
      paths:
      - backend:
          service:
            name: python-flask-service
            port:
              number: 9595
        path: /
        pathType: ImplementationSpecific


